import {
  Dumbbell,
  ShoppingBag,
  Bookmark,
  Shirt,
  PersonStanding,
  Layers,
  Wind,
  Footprints,
  Glasses,
  Scissors,
  Crown,
  Gem,
  Heart,
  Coffee,
  Moon,
  Waves,
  Briefcase,
  Tag,
  HelpCircle,
  Star,
  Sparkles,
  Droplets,
  Grid2x2,
  Package,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  Activewear: Dumbbell,
  Bags: ShoppingBag,
  Belts: Bookmark,
  Blazers: Briefcase,
  Bodysuits: PersonStanding,
  Cardigans: Shirt,
  Coats: Wind,
  Dresses: Sparkles,
  Footwear: Footprints,
  Glasses: Glasses,
  'Hair Accessories': Scissors,
  Hats: Crown,
  Hosiery: Grid2x2,
  Jackets: Shirt,
  Jeans: Shirt,
  Jewelry: Gem,
  Jumpsuits: PersonStanding,
  Lingerie: Heart,
  Loungewear: Coffee,
  Overalls: Shirt,
  Pants: Shirt,
  Robes: Moon,
  Rompers: Shirt,
  Scarves: Wind,
  Shapewear: Layers,
  Shorts: Shirt,
  Shrugs: Shirt,
  Skirts: Star,
  Sleepwear: Moon,
  Suits: Briefcase,
  Sweaters: Shirt,
  Sweatshirts: Shirt,
  Swimwear: Waves,
  Ties: Droplets,
  Tops: Shirt,
  Underwear: Heart,
  Vests: Shirt,
  Other: HelpCircle,
  'Other Accessories': Tag,
}

export function getCategoryIcon(category: string): LucideIcon {
  return CATEGORY_ICONS[category] ?? Package
}
